[build]
  # For static HTML/CSS/JS (no build): leave command empty
  publish = "."

# Pretty caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page (if you have 404.html)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
